### ISSUE TITLE
Pyanote.audio (svc pre-sd) does not use the GPU by default

### ISSUE THREAD

**Issue by ShinyJustyZ** [voicepaw/so-vits-svc-fork#1007]
### Describe the bug

The 'svc pre-sd' command does not use the CUDA GPU by default, and uses the cpu instead which is really slow. I found this out after I tried the fix by AmazingSlab ( #471 scroll to the very bottom).
```
if pipeline is None:
    raise ValueError("Failed to load pipeline")
pipeline = pipeline.to(torch.device("cuda"))
LOG.info(f"Processing {input_path}. This may take a while...")
diarization = pipeline(
    input_path, min_speakers=min_speakers, max_speakers=max_speakers
)
```
I replaced the default code (before line 38 on `preprocessing/preprocess_speaker_diarization.py`) with this one and it started using the GPU. Before the fix, it took more than an hour to proccess, but with the replacement, it finished in less than a minute. 

### To Reproduce

Use the default code

### Version

4.1.23

### Platform

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by 34j** [comment]
You can send a simple PR for this.
