### ISSUE TITLE
colab Copy configs file err

### ISSUE THREAD

**Issue by xiguazhiPrince** [voicepaw/so-vits-svc-fork#1035]
### Describe the bug

![image](https://github.com/voicepaw/so-vits-svc-fork/assets/34903051/555c8d84-48fd-45e2-beee-8ae624bd1c10)

cp: cannot stat 'configs/44k/config.json': No such file or directory

### To Reproduce

Uploaded 3 own audio, 10s each.

### Version

so-vits-svc-fork-4.0.ipynb

### Platform

colab 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by Fyphen1223** [comment]
I'm facing the extact problem.

Have you seen an error message like this?

```
```

**Comment by Fyphen1223** [comment]
Because this might be cause, which corrupting entire program.

**Comment by DealWithArany** [comment]
> I'm facing the extact problem.
> 
> Have you seen an error message like this?
> 
> ```
> Preprocessing:   0% 0/1 [00:00<?, ?it/s][02:57:15] WARNING  [02:57:15]                                                       
> ```

Same problem.....

**Comment by DealWithArany** [comment]
Somehow he solved it, but he didn't writed it down D:
https://github.com/voicepaw/so-vits-svc-fork/issues/981

**Comment by xiguazhiPrince** [comment]
> Somehow he solved it, but he didn't writed it down D: #981

I think it's because I have such a small number of datasets. I'll just add a few more audio files
