### ISSUE TITLE
Slower Training Time with Dual GPUs Compared to Single GPU

### ISSUE THREAD

**Issue by TickToTock** [voicepaw/so-vits-svc-fork#1230]
### Describe the bug

I am experiencing slower training times when using two 2080 Ti GPUs compared to a single 2080 Ti GPU for the same Sovits dataset. Here are the details:

Setup: Training on a single 2080 Ti GPU vs. dual 2080 Ti GPUs.
Batch Size and Training Parameters: Identical for both setups.
Observation: When using dual 2080 Ti GPUs, CPU RAM usage doubles, and both GPUs show consistent GPU memory usage compared to single GPU training. However, the training speed has decreased.
Single GPU: Approximately 290 seconds per epoch.
Dual GPUs: Approximately 373 seconds per epoch, despite doubling resource and power consumption.

Questions:
What are the main advantages of multi-GPU training? 
Are there any potential issues with my training parameters or setup that might be causing the slower performance?
I would appreciate any help or insights on this issue. Thank you!

![1gpu-set01](https://github.com/user-attachments/assets/d945e6ce-604e-41cf-80ef-f99563eee126)
![1gpu-perf01](https://github.com/user-attachments/assets/b77967c5-0b34-4952-b451-1c2f47c64552)
![2gpu-set01](https://github.com/user-attachments/assets/8aca0396-772a-484e-a20e-c4d0a0a00a88)
![2gpu-perf02](https://github.com/user-attachments/assets/f68aae4d-d525-49d5-b398-36a14e324710)

### To Reproduce

Slower Training Time with Dual GPUs Compared to Single GPU

### Version

latest

### Platform

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by 34j** [comment]
I think you are sending an issue to the wrong repository. I would recommend you send this to the original one.
