### ISSUE TITLE
How to inference to all voice files in the directory

### ISSUE THREAD

**Issue by kdrkdrkdr** [voicepaw/so-vits-svc-fork#129]
**Describe the bug**

**To Reproduce**

**Additional context**

"svc infer" This command can only be one file at a time. Is there a way to infer to multiple files at once?

**Comment by Satisfy256** [comment]
If you know a bit of python, you can run a script like this and edit the variables inside the script.

`import os
import subprocess

directory = 'D:/testfiles/wavs'
modelpath = 'D:/testfiles/logs/44k/G_12345.pth'
configpath = 'D:/testfiles/configs/44k/config.json'

for filename in os.listdir(directory):
    f = os.path.join(directory, filename)
    if os.path.isfile(f):
        subprocess.run([
        "svc",
        "infer",
        "-m", f"{modelpath}",
        "-c", f"{configpath}",
        f"{f}"
        ])`
