### ISSUE TITLE
Training Errors circular import

### ISSUE THREAD

**Issue by Skeebos** [voicepaw/so-vits-svc-fork#204]
Having several errors when training a few seconds in:

ImportError: cannot import name 'notf' from 'tensorboard.compat'
ModuleNotFoundError: No module named 'chardet'
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)

Any help or ideas?

**Comment by 34j** [comment]
Resolved?
