### ISSUE TITLE
legacy_final proj is deprecated

### ISSUE THREAD

**Issue by ZeroHackz** [voicepaw/so-vits-svc-fork#247]
**Describe the bug**
Realtime translation isn't outputting audio. I'm keep getting this warning too: `legacy_final proj is deprecated`

**To Reproduce**

1. Launch the GUI
2. Set your presets
3. (Re)Start Voice Changer
4. Wait for it to actively listen to your mic
5. Speakng into the mic will result into this ' legacy_final_proj '-warning

**I've been using this software for weeks succesfully and love it to bits. Shame I can't get any audio output anymore. Any tips?**

**Things I've tried:**

- remove conda environment completely and create a new one
- removed conda environment and use venv instead
- removed conda and venv environemts and use local pc
- Downloaded the latest release v3.0.4 and pip installed the *[y.whl](https://github.com/34j/so-vits-svc-fork/releases/download/v3.0.4/so_vits_svc_fork-3.0.4-py3-none-any.whl) file. 
- Switching audio and inputs (using voice meeter) 

All led to the same warning and no output after starting voice changer..

**Comment by ZeroHackz** [comment]
![image](https://user-images.githubusercontent.com/15729496/230620562-621646ad-8deb-4f25-b4bb-f027c55c52b2.png)

**Comment by ZeroHackz** [comment]
![legacyy_final_proj is deprecated](https://user-images.githubusercontent.com/15729496/230620664-14fd3cc8-633c-40a2-aa76-953334d0c0c0.png)

**Comment by 34j** [comment]
I don't think that caution is relevant. (Sorry for the confusion.) Can you post the complete output?

**Comment by ZeroHackz** [comment]
Had no other errors, seems my voicemeeter settings are messing it up. Ticket can be closed.
