### ISSUE TITLE
bat file fails install the package

### ISSUE THREAD

**Issue by wweziza** [voicepaw/so-vits-svc-fork#284]
Im using the one-click installer, everything fine untill it installing so-vits-svc-fork. It return

 `ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.8,<3.11; 0.2.0 Requires-Python >=3.8,<3.11; 0.2.1 Requires-Python >=3.8,<3.11; 0.3.0 Requires-Python >=3.8,<3.11; 0.4.0 Requires-Python >=3.8,<3.11; 0.4.1 Requires-Python >=3.8,<3.11; 0.5.0 Requires-Python >=3.8,<3.11; 0.6.0 Requires-Python >=3.8,<3.11; 0.6.1 Requires-Python >=3.8,<3.11; 0.6.2 Requires-Python >=3.8,<3.11; 0.6.3 Requires-Python >=3.8,<3.11; 0.7.1 Requires-Python >=3.8,<3.11; 0.8.0 Requires-Python >=3.8,<3.11; 0.8.1 Requires-Python >=3.8,<3.11; 0.8.2 Requires-Python >=3.8,<3.11; 1.0.0 Requires-Python >=3.8,<3.11; 1.0.1 Requires-Python >=3.8,<3.11; 1.0.2 Requires-Python >=3.8,<3.11; 1.1.0 Requires-Python >=3.8,<3.11; 1.1.1 Requires-Python >=3.8,<3.11; 1.2.0 Requires-Python >=3.8,<3.11; 1.2.1 Requires-Python >=3.8,<3.11; 1.2.10 Requires-Python >=3.8,<3.11; 1.2.11 Requires-Python >=3.8,<3.11; 1.2.2 Requires-Python >=3.8,<3.11; 1.2.3 Requires-Python >=3.8,<3.11; 1.2.4 Requires-Python >=3.8,<3.11; 1.2.5 Requires-Python >=3.8,<3.11; 1.2.6 Requires-Python >=3.8,<3.11; 1.2.7 Requires-Python >=3.8,<3.11; 1.2.8 Requires-Python >=3.8,<3.11; 1.2.9 Requires-Python >=3.8,<3.11; 1.3.0 Requires-Python >=3.8,<3.11; 1.3.1 Requires-Python >=3.8,<3.11; 1.3.2 Requires-Python >=3.8,<3.11; 1.3.3 Requires-Python >=3.8,<3.11; 1.3.4 Requires-Python >=3.8,<3.11; 1.3.5 Requires-Python >=3.8,<3.11; 1.3.6 Requires-Python >=3.8,<3.11; 1.4.0 Requires-Python >=3.8,<3.11; 1.4.1 Requires-Python >=3.8,<3.11; 1.4.2 Requires-Python >=3.8,<3.11; 1.4.3 Requires-Python >=3.8,<3.11; 2.0.0 Requires-Python >=3.8,<3.11; 2.1.0 Requires-Python >=3.8,<3.11; 2.1.1 Requires-Python >=3.8,<3.11; 2.1.2 Requires-Python >=3.8,<3.11; 2.1.3 Requires-Python >=3.8,<3.11; 2.1.4 Requires-Python >=3.8,<3.11; 2.1.5 Requires-Python >=3.8,<3.11; 3.0.0 Requires-Python >=3.8,<3.11; 3.0.1 Requires-Python >=3.8,<3.11; 3.0.2 Requires-Python >=3.8,<3.11; 3.0.3 Requires-Python >=3.8,<3.11; 3.0.4 Requires-Python >=3.8,<3.11; 3.0.5 Requires-Python >=3.8,<3.11; 3.1.0 Requires-Python >=3.8,<3.11; 3.1.1 Requires-Python >=3.8,<3.11; 3.1.2 Requires-Python >=3.8,<3.11; 3.1.3 Requires-Python >=3.8,<3.11; 3.1.4 Requires-Python >=3.8,<3.11; 3.1.5 Requires-Python >=3.8,<3.11; 3.1.6 Requires-Python >=3.8,<3.11; 3.1.7 Requires-Python >=3.8,<3.11; 3.1.8 Requires-Python >=3.8,<3.11; 3.1.9 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement so-vits-svc-fork (from versions: none)
ERROR: No matching distribution found for so-vits-svc-fork`

**Comment by ujicos** [comment]
I had the same issue and simply uninstalled 3.11 and manually installed 3.10.10, this "fixed it"
I am now on: Launching so-vits-svc-fork GUI...
Traceback (most recent call last):
  File "C:\Users\gay ming\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\gay ming\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "H:\cudnn-windows-x86_64-8.8.1.3_cuda11-archive\venv\Scripts\svcg.exe\__main__.py", line 4, in <module>
  File "H:\cudnn-windows-x86_64-8.8.1.3_cuda11-archive\venv\lib\site-packages\so_vits_svc_fork\gui.py", line 12, in <module>
    import torch
  File "H:\cudnn-windows-x86_64-8.8.1.3_cuda11-archive\venv\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "H:\cudnn-windows-x86_64-8.8.1.3_cuda11-archive\venv\lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies.

(However i am looking at other issues to see if its listed, so ill likely resolve this quick)

**Comment by wweziza** [comment]
It worked when i manually installed 3.10.10 python.
