### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 26136) exited unexpectedly

### ISSUE THREAD

**Issue by embis2003** [voicepaw/so-vits-svc-fork#373]
I was training overnight and wanted to wake up to some progress, but it hit this exception shortly after falling asleep, please fix this issue

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/59685827/232495085-776a4897-c194-4e47-b313-3cbf4108c1db.png">

**Comment by 34j** [comment]
Try reducing `num_workers`.
