### ISSUE TITLE
install.bat should pause

### ISSUE THREAD

**Issue by vitacon** [voicepaw/so-vits-svc-fork#374]
I was so naive that I ran "install.bat" directly from Explorer at first. It started to do something and then the window just disappeared. It took me a few minutes to realize that I should have run it from a console window to see error messages. =]

I think it would be useful to add some "pause" to let users find out what went wrong.

**Comment by xieyumc** [comment]
Yes, i had the same problem, so I have made a new version that replace "exit" with "pause",I think I can create a pull request to fix it
