### ISSUE TITLE
error in ubuntu when doing pip install -U torch torchaudio

### ISSUE THREAD

**Issue by Blacksingh** [voicepaw/so-vits-svc-fork#397]
error in ubuntu when doing
pip install -U torch torchaudio --index-url https://download.pytorch.org/whl/cu118

pip install -U torch torchaudio --index-url https://download.pytorch.org/whl/cu118
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch
  Downloading https://download.pytorch.org/whl/cu118/torch-2.0.0%2Bcu118-cp310-cp310-linux_x86_64.whl (2267.3 MB)
     ╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/2.3 GB 26.8 MB/s eta 0:01:24
ERROR: Wheel 'torch' located at /tmp/pip-unpack-17q_1ip0/torch-2.0.0+cu118-cp310-cp310-linux_x86_64.whl is invalid.

**Comment by krzysiek546** [comment]
Try this command: 

`pip install -U torch torchaudio`
