### ISSUE TITLE
Does this project only support torch 2.0 and CUDA >= 11.8?

### ISSUE THREAD

**Issue by ViewWholeWorld** [voicepaw/so-vits-svc-fork#400]
Hi, I have installed this project successfully, and I also can infer data, but when I train a model on my own data, I got some pytroch error. I am working on a server that is installed CUDA 11.2, does this project only support torch 2.0 and CUDA >= 11.8? 

btw, Thanks for your excellent working!

**Comment by 34j** [comment]
That is all we **officially** support.

**Comment by ViewWholeWorld** [comment]
> 

I upgrade my Nvidia driver and CUDA version, and the project works fine, thanks for your reply.
