### ISSUE TITLE
spk Key Error when selecting config file in gui

### ISSUE THREAD

**Issue by Sagylel** [voicepaw/so-vits-svc-fork#407]
Hey guys, im having an issue when selecting a model config file. Right after I select the config the gui stops and consoles gives this error:
`Traceback (most recent call last):
  File "C:\Users\demir\anaconda3\envs\so-vits-fork\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\demir\anaconda3\envs\so-vits-fork\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\demir\anaconda3\envs\so-vits-fork\Scripts\svcg.exe\__main__.py", line 7, in <module>
  File "C:\Users\demir\anaconda3\envs\so-vits-fork\lib\site-packages\so_vits_svc_fork\gui.py", line 544, in main
    update_speaker()
  File "C:\Users\demir\anaconda3\envs\so-vits-fork\lib\site-packages\so_vits_svc_fork\gui.py", line 448, in update_speaker
    values=list(hp.__dict__["spk"].keys()), set_to_index=0
KeyError: 'spk'`

[I am using this voice model.](https://huggingface.co/huggingartists/xxxtentacion)
![image](https://user-images.githubusercontent.com/31561692/233138276-f4c1b993-7d0d-48bb-a280-480b1c7b574b.png)

**Comment by Lordmau5** [comment]
What model did you try to load? To me this looks like an unsupported model file, seeing as the ones for v4.0-v1 all include a `"spk"` entry in the config file

**Comment by Sagylel** [comment]
> What model did you try to load? Can you provide a link to it perhaps? To me this looks like an unsupported model file, seeing as the ones for v4.0-v1 all include a `"spk"` entry in the config file

I just cloned this project and used the config.json and the model file https://huggingface.co/huggingartists/xxxtentacion

**Comment by BlueAmulet** [comment]
that is a GPT-2 model.

**Comment by Sagylel** [comment]
> that is a GPT-2 model.

💀 💀 💀 
Am i supposed to train my own model for it then? Or is there a site i can grab models from?

**Comment by Lordmau5** [comment]
Seeing as the original issue has been resolved since it's a model in an unsupported format, I'm gonna go ahead and close it.

feel free to open a new one if you encounter any issues though! 😁
