### ISSUE TITLE
CUDA and PyTorch installed but not detected

### ISSUE THREAD

**Issue by lucellent** [voicepaw/so-vits-svc-fork#408]
I have installed Cuda and Pytorch multiple times yet So-Vits doesn't detect them, nor my GPU (the GUI inference doesn't let me use GPU and training is very slow, I was able to use the GPU to train a few days ago but had to reset Windows)

I can verify Cuda with nvcc --version and it shows as version 12.1
Same with PyTorch

and yes, I restarted the PC before testing again

**Comment by Lordmau5** [comment]
Cuda in nvcc doesn't show the correct version.
It shows the newest available (which in that case comes from the normal display driver)

Do you have CUDA 11.7/8 files in one of the NVIDIA branded subfolders in `C:\Program Files\`?

Please also make sure you have cuDNN additionally to the CUDA toolkit

**Comment by lucellent** [comment]
I have Cuda 12.1 folder in Program Files
but I think I don't have cuDNN, will install now and let you know

**Comment by Lordmau5** [comment]
Cuda 12.1 isn't supported from what I know, only 11.7 and 11.8.

Can you try installing one of those?

**Comment by krzysiek546** [comment]
I had same problem and I uninstalled torch and torchaudio. After that I installed torch from this prompt `conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia` plus missing libriaries and gpu was detected.

**Comment by lucellent** [comment]
I tried what @krzysiek546 suggested and something else broke lol so I completely reinstalled so-vits again and seems like GPU works now! Still not sure what exactly might've fixed the issue, but downgrading Cuda probably was something that had to be done either way.

Thanks to both of you!
