### ISSUE TITLE
pre-resample not running

### ISSUE THREAD

**Issue by forerunrun** [voicepaw/so-vits-svc-fork#448]
i'm trying to run svc-pre-resample but this is resulting in the following...
Preprocessing: 0it [00:00, ?it/s]
there is no progress and the operation stops after this log, is there a known cause for why this may be happening and a possible fix? this was running fine yesterday, i'm trying everything to get it working again, uninstalling all references to python and pip and trying again, has anyone encountered this and is there an obvious resolve i'm missing?

UPDATE: i went round in circles for hourse before realising that the samples were directly in dataset_raw folder, they need to be in a subdirectory within dataset_raw

dataset_raw->audioSamples->sample1.wav

this works, closing issue

**Comment by mathisfouques** [comment]
(Thanks for this issue, was having the same problem)
