### ISSUE TITLE
Configurable output file

### ISSUE THREAD

**Issue by alexanderkoumis** [voicepaw/so-vits-svc-fork#452]
The output file is not configurable. This becomes a problem when you output a file, open it up in a DAW (e.g. FL Studio), and want to bounce out a new converted voice file, causing a crash while writing because the file handle is still held by the DAW.

Recommended features:
- A new output text box that allows specifying the output file
- The default output filename should follow the same `.out` pattern as before, but have an automatically incrementing index if the output file already exists.

I've already implemented this and will be submitting a pull request shortly.

**Comment by Arthur-McArthur** [comment]
how can we get the automatic increment filename to work?

**Comment by alexanderkoumis** [comment]
> how can we get the automatic increment filename to work?

This mechanism is triggered when the input file is selected, causing the default output filename to be generated. It guarantees the default output filename is unique when first generated. However, if inference is run multiple times with the same auto-generated output filename, the old tracks will be overwritten.

**Comment by Arthur-McArthur** [comment]
Thanks, it would be very useful if the output filename would automatically increment itself. File-out_2, File-out_3 etc. As it stands, if you intend to create multiple files you have to rename or move them after each inference which is inconvenient.
