### ISSUE TITLE
Vram Memory limit problem

### ISSUE THREAD

**Issue by slim1592** [voicepaw/so-vits-svc-fork#469]
I have this problem. how to solve it. Thanks
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 1.55 GiB already allocated; 0 bytes free; 1.71 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by krzysiek546** [comment]
In default setting inference takes something around 3.5GB of vram. Sorry, but only solution for you is upgrading gpu with more vram or use colab or something like that.

**Comment by slim1592** [comment]
Thank you for your help
