### ISSUE TITLE
Old ckpts are not completely deleted in colab

### ISSUE THREAD

**Issue by Meldoner** [voicepaw/so-vits-svc-fork#474]
**Describe the bug**
In Google Colab ckpts are moved to trash, but not completely deleted, so you have to manually delete them, it should be automatically removed from the trash

**To Reproduce**
Start training in colab and wait

**Additional context**
you can implement it this way, we overwrite our ckpt file with 0 bytes and delete it, the file will remain in the trash, but it will no longer take up space
```
filepath = 'drive/MyDrive/so-vits-svc-fork/logs/44k/G_STEPS.pth'
open(filepath, 'w').close()
!rm {filepath} #(or what you use to remove)
```

**Comment by 34j** [comment]
You can send a PR🙂
