### ISSUE TITLE
cant run "pip install -U so-vits-svc-fork"

### ISSUE THREAD

**Issue by SundaePixel** [voicepaw/so-vits-svc-fork#475]
I tried to run command "pip install -U so-vits-svc-fork" and it gave this error below

-----------------------
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.8,<3.11; 0.2.0 Requires-Python >=3.8,<3.11; 0.2.1 Requires-Python >=3.8,<3.11; 0.3.0 Requires-Python >=3.8,<3.11; 0.4.0 Requires-Python >=3.8,<3.11; 0.4.1 Requires-Python >=3.8,<3.11; 0.5.0 Requires-Python >=3.8,<3.11; 0.6.0 Requires-Python >=3.8,<3.11; 0.6.1 Requires-Python >=3.8,<3.11; 0.6.2 Requires-Python >=3.8,<3.11; 0.6.3 Requires-Python >=3.8,<3.11; 0.7.1 Requires-Python >=3.8,<3.11; 0.8.0 Requires-Python >=3.8,<3.11; 0.8.1 Requires-Python >=3.8,<3.11; 0.8.2 Requires-Python >=3.8,<3.11; 1.0.0 Requires-Python >=3.8,<3.11; 1.0.1 Requires-Python >=3.8,<3.11; 1.0.2 Requires-Python >=3.8,<3.11; 1.1.0 Requires-Python >=3.8,<3.11; 1.1.1 Requires-Python >=3.8,<3.11; 1.2.0 Requires-Python >=3.8,<3.11; 1.2.1 Requires-Python >=3.8,<3.11; 1.2.10 Requires-Python >=3.8,<3.11; 1.2.11 Requires-Python >=3.8,<3.11; 1.2.2 Requires-Python >=3.8,<3.11; 1.2.3 Requires-Python >=3.8,<3.11; 1.2.4 Requires-Python >=3.8,<3.11; 1.2.5 Requires-Python >=3.8,<3.11; 1.2.6 Requires-Python >=3.8,<3.11; 1.2.7 Requires-Python >=3.8,<3.11; 1.2.8 Requires-Python >=3.8,<3.11; 1.2.9 Requires-Python >=3.8,<3.11; 1.3.0 Requires-Python >=3.8,<3.11; 1.3.1 Requires-Python >=3.8,<3.11; 1.3.2 Requires-Python >=3.8,<3.11; 1.3.3 Requires-Python >=3.8,<3.11; 1.3.4 Requires-Python >=3.8,<3.11; 1.3.5 Requires-Python >=3.8,<3.11; 1.3.6 Requires-Python >=3.8,<3.11; 1.4.0 Requires-Python >=3.8,<3.11; 1.4.1 Requires-Python >=3.8,<3.11; 1.4.2 Requires-Python >=3.8,<3.11; 1.4.3 Requires-Python >=3.8,<3.11; 2.0.0 Requires-Python >=3.8,<3.11; 2.1.0 Requires-Python >=3.8,<3.11; 2.1.1 Requires-Python >=3.8,<3.11; 2.1.2 Requires-Python >=3.8,<3.11; 2.1.3 Requires-Python >=3.8,<3.11; 2.1.4 Requires-Python >=3.8,<3.11; 2.1.5 Requires-Python >=3.8,<3.11; 3.0.0 Requires-Python >=3.8,<3.11; 3.0.1 Requires-Python >=3.8,<3.11; 3.0.2 Requires-Python >=3.8,<3.11; 3.0.3 Requires-Python >=3.8,<3.11; 3.0.4 Requires-Python >=3.8,<3.11; 3.0.5 Requires-Python >=3.8,<3.11; 3.1.0 Requires-Python >=3.8,<3.11; 3.1.1 Requires-Python >=3.8,<3.11; 3.1.10 Requires-Python >=3.8,<3.11; 3.1.11 Requires-Python >=3.8,<3.11; 3.1.12 Requires-Python >=3.8,<3.11; 3.1.13 Requires-Python >=3.8,<3.11; 3.1.2 Requires-Python >=3.8,<3.11; 3.1.3 Requires-Python >=3.8,<3.11; 3.1.4 Requires-Python >=3.8,<3.11; 3.1.5 Requires-Python >=3.8,<3.11; 3.1.6 Requires-Python >=3.8,<3.11; 3.1.7 Requires-Python >=3.8,<3.11; 3.1.8 Requires-Python >=3.8,<3.11; 3.1.9 Requires-Python >=3.8,<3.11; 3.10.0 Requires-Python >=3.8,<3.11; 3.10.1 Requires-Python >=3.8,<3.11; 3.10.2 Requires-Python >=3.8,<3.11; 3.10.3 Requires-Python >=3.8,<3.11; 3.10.4 Requires-Python >=3.8,<3.11; 3.10.5 Requires-Python >=3.8,<3.11; 3.11.0 Requires-Python >=3.8,<3.11; 3.2.0 Requires-Python >=3.8,<3.11; 3.3.0 Requires-Python >=3.8,<3.11; 3.3.1 Requires-Python >=3.8,<3.11; 3.4.0 Requires-Python >=3.8,<3.11; 3.5.0 Requires-Python >=3.8,<3.11; 3.5.1 Requires-Python >=3.8,<3.11; 3.6.0 Requires-Python >=3.8,<3.11; 3.6.1 Requires-Python >=3.8,<3.11; 3.6.2 Requires-Python >=3.8,<3.11; 3.7.0 Requires-Python >=3.8,<3.11; 3.7.1 Requires-Python >=3.8,<3.11; 3.7.2 Requires-Python >=3.8,<3.11; 3.7.3 Requires-Python >=3.8,<3.11; 3.8.0 Requires-Python >=3.8,<3.11; 3.8.1 Requires-Python >=3.8,<3.11; 3.9.0 Requires-Python >=3.8,<3.11; 3.9.1 Requires-Python >=3.8,<3.11; 3.9.2 Requires-Python >=3.8,<3.11; 3.9.3 Requires-Python >=3.8,<3.11; 3.9.4 Requires-Python >=3.8,<3.11; 3.9.5 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement so-vits-svc-fork (from versions: none)
ERROR: No matching distribution found for so-vits-svc-fork

**Comment by unpeekabl3** [comment]
i have same problem

**Comment by unpeekabl3** [comment]
I found a solution to this problem, download the python version from 3.8 to 3.11

**Comment by unpeekabl3** [comment]
I found a solution to this problem, download the python version from 3.8 to 3.11. I installed python version 3.8.0 and everything downloaded

**Comment by SundaePixel** [comment]
> I found a solution to this problem, download the python version from 3.8 to 3.11. I installed python version 3.8.0 and everything downloaded

Did this problem also fix "svcg" not being found when trying to open gui?
