### ISSUE TITLE
Can I train without using a pre-trained model?

### ISSUE THREAD

**Issue by SayaSS** [voicepaw/so-vits-svc-fork#479]
Thank you very much for your great work!
I have a lot of voice datasets, so I want to train without using a pre-trained model. How should I do it? Could I just directly comment out this line?
https://github.com/voicepaw/so-vits-svc-fork/blob/4af1ee8f77f46cbdd2a7dd8d7ed923315d609cd8/src/so_vits_svc_fork/train.py#L76

**Comment by 34j** [comment]
Yes.

**Comment by xieyumc** [comment]
Yes,but the training time will be longer

**Comment by kouropalatisk** [comment]
> Thank you very much for your great work! I have a lot of voice datasets, so I want to train without using a pre-trained model. How should I do it? Could I just directly comment out this line?
> 
> https://github.com/voicepaw/so-vits-svc-fork/blob/4af1ee8f77f46cbdd2a7dd8d7ed923315d609cd8/src/so_vits_svc_fork/train.py#L76

Hi SayaSS, what is the actual command to train without using a pre-trained model?
I've put: utils.ensure_pretrained_model(model_path, hparams.model.get("type_", "hifi-gan")) 
and it gave back: 'utils.ensure_pretrained_model' is not recognized as an internal or external command,
operable program or batch file.

I've put: so-vits-svc-fork/src/so_vits_svc_fork/train.py
and it gave back instructions about what pre-config, pre-hubert, pre-resample, etc do.

So what is the actual command to train without using a pre-trained model?!
(thank you!)

**Comment by SayaSS** [comment]
> > Thank you very much for your great work! I have a lot of voice datasets, so I want to train without using a pre-trained model. How should I do it? Could I just directly comment out this line?
> > https://github.com/voicepaw/so-vits-svc-fork/blob/4af1ee8f77f46cbdd2a7dd8d7ed923315d609cd8/src/so_vits_svc_fork/train.py#L76
> 
> Hi SayaSS, what is the actual command to train without using a pre-trained model? I've put: utils.ensure_pretrained_model(model_path, hparams.model.get("type_", "hifi-gan")) and it gave back: 'utils.ensure_pretrained_model' is not recognized as an internal or external command, operable program or batch file.
> 
> I've put: so-vits-svc-fork/src/so_vits_svc_fork/train.py and it gave back instructions about what pre-config, pre-hubert, pre-resample, etc do.
> 
> So what is the actual command to train without using a pre-trained model?! (thank you!)

You need to edit the package's source code in your Python environment.
https://stackoverflow.com/questions/23075397/python-how-to-edit-an-installed-package

And comment out or delete this line.
```python
#utils.ensure_pretrained_model(model_path, hparams.model.get("type_", "hifi-gan")) 
```

Then you can use it just like the normal training steps.

**Comment by kouropalatisk** [comment]
> > > Thank you very much for your great work! I have a lot of voice datasets, so I want to train without using a pre-trained model. How should I do it? Could I just directly comment out this line?
> > > https://github.com/voicepaw/so-vits-svc-fork/blob/4af1ee8f77f46cbdd2a7dd8d7ed923315d609cd8/src/so_vits_svc_fork/train.py#L76
> > 
> > 
> > Hi SayaSS, what is the actual command to train without using a pre-trained model? I've put: utils.ensure_pretrained_model(model_path, hparams.model.get("type_", "hifi-gan")) and it gave back: 'utils.ensure_pretrained_model' is not recognized as an internal or external command, operable program or batch file.
> > I've put: so-vits-svc-fork/src/so_vits_svc_fork/train.py and it gave back instructions about what pre-config, pre-hubert, pre-resample, etc do.
> > So what is the actual command to train without using a pre-trained model?! (thank you!)
> 
> You need to edit the package's source code in your Python environment. https://stackoverflow.com/questions/23075397/python-how-to-edit-an-installed-package
> 
> And comment out or delete this line.
> 
> ```python
> #utils.ensure_pretrained_model(model_path, hparams.model.get("type_", "hifi-gan")) 
> ```
> 
> Then you can use it just like the normal training steps.

thank you for replying back!
So after I edit the package (fingers crossed) then by running the command "svc train -t" it'll train without a pre-trained model.

I'll definatelly have a close look at your link as I know nothing about coding!!

**Comment by nabeelimran** [comment]
> Thank you very much for your great work! I have a lot of voice datasets, so I want to train without using a pre-trained model. How should I do it? Could I just directly comment out this line?
> 
> https://github.com/voicepaw/so-vits-svc-fork/blob/4af1ee8f77f46cbdd2a7dd8d7ed923315d609cd8/src/so_vits_svc_fork/train.py#L76

Hi SayaSS, just want to know, can we use pre trained model directly for inference or we have to train them more?
I've looked into some pre trained models which provide G.pth, D.pth and config file, how can i use them to refer only?

**Comment by SayaSS** [comment]
> > Thank you very much for your great work! I have a lot of voice datasets, so I want to train without using a pre-trained model. How should I do it? Could I just directly comment out this line?
> > https://github.com/voicepaw/so-vits-svc-fork/blob/4af1ee8f77f46cbdd2a7dd8d7ed923315d609cd8/src/so_vits_svc_fork/train.py#L76
> 
> Hi SayaSS, just want to know, can we use pre trained model directly for inference or we have to train them more? I've looked into some pre trained models which provide G.pth, D.pth and config file, how can i use them to refer only?


The pre-trained model provided by this repo, which is intended for training, has removed some weights related to inference and cannot be used for inference directly. However, the ones you find should work, and inference only requires G.pth and config.json.
https://github.com/voicepaw/so-vits-svc-fork#inference
