### ISSUE TITLE
Optimizations for the project

### ISSUE THREAD

**Issue by gitihobo** [voicepaw/so-vits-svc-fork#483]
These are some ideas I have for the project

1. Bat file that automatically opens svc GUI
2. If file does cuda out of memory it loops the process but cuts file into multiple pieces so it doesn't fail this time
3. Bulk infer for multiple audio files back to back
4. Easy way to change default training directories
5. Easy way to change default parameters like autoplay and +1 octave

**Comment by 34j** [comment]
I don't think these are worth implementing

**Comment by gitihobo** [comment]
Im a noob can you tell me how to do 5? 2 & 3 would be nice only if they can be done easily due to longer audio, a lot of my audio runs out of memory because its too many words, even if its only 2 minutes long.

**Comment by 34j** [comment]
Each Issue has been opened (and some closed), so please refer to it as appropriate.
