### ISSUE TITLE
Issue with svc pre-resample (need at most 63 handles, got a sequence of length 65)

### ISSUE THREAD

**Issue by definatefilms** [voicepaw/so-vits-svc-fork#504]
Having an issue at the step where we run "svc pre-resample". The process doesn't complete and displays the error below. It does create a folder (44K within dataset) with some audio files processed but not all. We are using the folder dataset_raw that we created that has the original files split into files that are less then 10 seconds each.

Current Device Used: 
A6000 GPU THREADRIPPER PRO 32 CORE 
RUNNING WINDOWS 10 or 11 (Tried on 2 different identical computers)

How do we fix this?

______________________________________________________________________________

(so-vits-fork-new) C:\Users\defin\Downloads\so-vits-svc-fork-main\so-vits-svc-fork-main> svc pre-resample
Preprocessing:   0%|                                                                           | 0/195 [00:00<?, ?it/s]Exception in thread ExecutorManagerThread:
Traceback (most recent call last):
  File "C:\Users\defin\anaconda3\envs\so-vits-fork-new\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\defin\anaconda3\envs\so-vits-fork-new\lib\site-packages\joblib\externals\loky\process_executor.py", line 557, in run
    result_item, is_broken, bpe = self.wait_result_broken_or_wakeup()
  File "C:\Users\defin\anaconda3\envs\so-vits-fork-new\lib\site-packages\joblib\externals\loky\process_executor.py", line 611, in wait_result_broken_or_wakeup
    ready = wait(readers + worker_sentinels)
  File "C:\Users\defin\anaconda3\envs\so-vits-fork-new\lib\multiprocessing\connection.py", line 879, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "C:\Users\defin\anaconda3\envs\so-vits-fork-new\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 65

**Comment by 34j** [comment]
https://github.com/python/cpython/issues/89240

**Comment by 34j** [comment]
As of now, you can specify n_jobs like -n 60 to fix this issue.

**Comment by definatefilms** [comment]
> As of now, you can manually specify n_jobs like -n 60 to fix this issue.

I went into "preprocess_resample.py" and changed njobs from -1 to 60 and still getting the same error. I also tried it as 30.

**Comment by 34j** [comment]
What about 1?

**Comment by definatefilms** [comment]
> What about 1?

still getting same error when i set njobs to 1. shown below:

def preprocess_resample(
    input_dir: Path | str,
    output_dir: Path | str,
    sampling_rate: int,
    n_jobs: int = 1,
    *,
    top_db: int = 30,
    frame_seconds: float = 0.1,
    hop_seconds: float = 0.05,
) -> None:
    input_dir = Path(input_dir)
    output_dir = Path(output_dir)
    """Preprocess audio files in input_dir and save them to output_dir."""

    print("*" * 80)
    print(f"N JOBS IS: {n_jobs}")
    traceback.print_stack()

**Comment by 34j** [comment]
`svc pre-resample -n 1`

**Comment by definatefilms** [comment]
> `svc pre-resample -n 1`

that did it! thanks
