### ISSUE TITLE
GUI Buttons to Infer not shown

### ISSUE THREAD

**Issue by DennLie** [voicepaw/so-vits-svc-fork#505]
**Describe the bug**
If i start the GUI with svcg everythings seems to be there except the buttons on the bottom.Not sure what i am missing or if its a bug.

**To Reproduce**
Steps to reproduce the behavior: svcg

**Additional context**
I trained a voice and everything is fine except i cant use the GUI and i have to use the console with svc infer +args instead.
<img width="842" alt="Screenshot 2023-04-28 134830" src="https://user-images.githubusercontent.com/50552332/235139910-7cf0a8b7-accc-4b96-8f0e-26ba05b0c634.png">
<img width="909" alt="Screenshot 2023-04-28 134130" src="https://user-images.githubusercontent.com/50552332/235139915-9b0b6eb3-ce53-41b3-83cd-64beffb61883.png">

**Comment by 34j** [comment]
Is it possible that it is simply out of view from the screen?

**Comment by DennLie** [comment]
I wish it was that easy but thats not the case
<img width="884" alt="Screenshot 2023-04-30 002504" src="https://user-images.githubusercontent.com/50552332/235326564-314a908a-4f6d-49ae-a170-bd865e41dc48.png">

**Comment by jaredp89** [comment]
I'm having this same problem. Anyone figure out a fix?

**Comment by 4EvaLuv** [comment]
huhh, same, ive rebuilt a bunch of times. same outcome

**Comment by jambgithub** [comment]
i am having the same problem, the GUI did not shown infer botton

**Comment by Diegoestropini** [comment]
I'm having the same problem. I had version 3.11 and it was working perfectly fine, but now that I updated it, the infer button disappeared. Does anyone know the solution?

**Comment by ayebrian** [comment]
same

**Comment by AnonX31st** [comment]
Yea, the infer button is missing for me too lol...

**Comment by GooDUnKnown** [comment]
same

**Comment by Chiquis146** [comment]
I've had the exact same problem too. Does anyone knows if a certain So-Vits version has a bug or has a certain requirement or maybe we have to install another version? I actually installed it in another computer and had the same outcome.

**Comment by anessxnouar** [comment]
facing the same issue , please try adding scalability to the GUI as a solution

**Comment by empukeyup** [comment]
I had version 3.15.0, the infer button not showing

**Comment by aonthebeatz** [comment]
same here, infer button not showin on 3.15.0

**Comment by AnonX31st** [comment]
For me it was a resolution issue. I fixed it by changing the resolution in my Window settings to a lower value.

**Comment by njpwwelp** [comment]
> For me it was a resolution issue. I fixed it by changing the resolution in my Window settings to a lower value.

I just tried fixing the resolution to my computer. That doesn't work. The infer button still doesn't show. I have no idea what the problem is.

**Comment by harby90** [comment]
same with me,,,,,

**Comment by empukeyup** [comment]
> For me it was a resolution issue. I fixed it by changing the resolution in my Window settings to a lower value.

what is the resolution value do you use? i use highest res in my device (1366x768), inver value not showing; when i try lower resolution 1280x7200, the preset name field also not showing, i thought we need higher resolution, not lower resolution

**Comment by higxshikxta** [comment]
I found a solution that worked well for me! I had my resolution set at 1440x900 with my scale at 125% and the infer button was nowhere to be found. The moment I switched my scale to 100%, they appeared! 

![image](https://github.com/voicepaw/so-vits-svc-fork/assets/134891447/3bbd5581-c97b-4e8b-b034-c9641b364e49)
![image](https://github.com/voicepaw/so-vits-svc-fork/assets/134891447/ad34f412-afe4-467a-aa05-e1848d84752b)

Give it a try if you're having the same problem!

**Comment by njpwwelp** [comment]
> I found a solution that worked well for me! I had my resolution set at 1440x900 with my scale at 125% and the infer button was nowhere to be found. The moment I switched my scale to 100%, they appeared!
> 
> ![image](https://user-images.githubusercontent.com/134891447/241592799-3bbd5581-c97b-4e8b-b034-c9641b364e49.png) ![image](https://user-images.githubusercontent.com/134891447/241592826-ad34f412-afe4-467a-aa05-e1848d84752b.png)
> 
> Give it a try if you're having the same problem!

I don't have that large of a resolution. My largest resolution is 1366x768. Also, my scale is 100%. The infer button still doesn't show up.

**Comment by 34j** [comment]
Please feel free to reopen if it is still not working.

**Comment by empukeyup** [comment]
> Please feel free to reopen this if it is still not working.

still not working

**Comment by njpwwelp** [comment]
> Please feel free to reopen this if it is still not working.

How do you fix the window scaling?

**Comment by njpwwelp** [comment]
> Please feel free to reopen this if it is still not working.

It works for me now!

**Comment by empukeyup** [comment]
> Please feel free to reopen this if it is still not working.

works after doing fresh install
