### ISSUE TITLE
pre-hubert -fm crepe step not working

### ISSUE THREAD

**Issue by pointave** [voicepaw/so-vits-svc-fork#542]
Running the 'svc pre-hubert -fm crepe' command will not complete. I used to be able to run it before I updated and it would take around 1-2 minutes for a 130 ten second sample dataset. 

Now on linux it runs for a few seconds sometimes even reaching around 100% and then gives an error of oom due to leaked semiphores. On windows I did get one to complete but it took around 20 minutes, but other datasets would crash my computer (bsod video_scheduler) and they were longer than 20 minutes. On wsl it seems to act similarly to windows where it will run but its much slower than windows so I havent gotten far enough for it to crash. Windows will run at full 24gb vram, not sure about linux since it seems to be at 8gb before I get the traceback error.

I can still run the 'svc pre-hubert' command but I dont think the quality is that good. Is there a way to install the old svc-fork?

**Comment by NanoCode012** [comment]
You can `pip install -U so-vits-svc-fork==...` replace it with your version.

**Comment by bux10** [comment]
Hi, I was having the same problem as the OP and was able to fix it by manually setting the number of workers on the pre-hubert command. The number of workers was automatically being set to 12, I assume this is based on the amount of VRAM available.
I used 'svc pre-hubert -n 6' to set a lower number of workers and it worked fine.

**Comment by pointave** [comment]
Finally got back to it and t
