### ISSUE TITLE
 Could not install packages due to an OSError: [WinError 206] The filename or extension is too long:

### ISSUE THREAD

**Issue by harrisonmount** [voicepaw/so-vits-svc-fork#574]
Happens with pip install so-vits-svc-fork

**Comment by yin3331** [comment]
open regedit in your pc，find”LongPathsEnabled“ under HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem，set the value to 1

![屏幕截图 2023-05-13 103848](https://github.com/voicepaw/so-vits-svc-fork/assets/32604161/9b2c3090-ec7d-4875-8040-60fcc5c2ecf9)
