### ISSUE TITLE
Problem with input file audio path format selection (gui.py)

### ISSUE THREAD

**Issue by sbersier** [voicepaw/so-vits-svc-fork#602]
SVC version: 3.14.1

Currently, format selection for the input audio path file doesn't allow for format selection and filter shows no audio files.

The problem is on line 352 of gui.py

I solved it by putting, on line 352:
`file_types=get_supported_file_types(),`

instead of the current:

`file_types=get_supported_file_types_concat(),`

This solved the problem for me. See before and after videos.
Before:

https://github.com/voicepaw/so-vits-svc-fork/assets/34165937/61801d33-9ca1-4cd3-a3ec-565b6f705f6d

After correction:

https://github.com/voicepaw/so-vits-svc-fork/assets/34165937/a8a630a4-10a8-40b7-ba35-2fb50595cc74

**Comment by 34j** [comment]
Another problem due to the different behavior between Linux and Windows 😇

**Comment by 34j** [comment]
```
if os.environ("OS") == "nt"...
```

**Comment by sbersier** [comment]
NOTE: My installed version on PySimpleGui is: 4.60.4
Do you have a more recent version?

**Comment by 34j** [comment]
I think it's an OS-specific problem, not PySimpleGUI

**Comment by sbersier** [comment]
Another problem... The checkboxes change when pressing on "infer"...
It only appears at first inference. The second time you press on "infer", that's good. :-D

https://github.com/voicepaw/so-vits-svc-fork/assets/34165937/ddfe0823-5bdc-46b3-8ca0-b7532274c891

**Comment by 34j** [comment]
> Another problem... The checkboxes change when pressing on "infer"... It only appears at first inference. The second time you press on "infer", that's good. :-D
> 
>  other.mp4

#95

**Comment by 34j** [comment]
Bug reports are appreciated, but note that you can also send PRs.
