### ISSUE TITLE
the "infer" button is missing

### ISSUE THREAD

**Issue by gulever666** [voicepaw/so-vits-svc-fork#701]
### Describe the bug

the infer button is missing 
I reinstalled the application but without changes
there are no errors in the command line
![image](https://github.com/voicepaw/so-vits-svc-fork/assets/99373605/acffa260-ccbb-48c9-86d8-7ad73a60cea0)

### To Reproduce

after opening the application, I add a voice and music model, but the button is missing

### Version

3.15.0

### Platform

Windows 10 Pro

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by 34j** [comment]
"I have checked existing issues to avoid duplicates." 🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔
