### ISSUE TITLE
infer problem

### ISSUE THREAD

**Issue by zdj97** [voicepaw/so-vits-svc-fork#739]
### Describe the bug

Everything i have done and used a checkpoint to infer.
When i run **svc vc -m XX -c XX**, the program is running.
However, when i said 'hello,hello', i hearded 'he', 'hello','hello,hell','hello,hello'....... Almost 4or5 times. 
What i expected is when i say 'hello,hello', i hear 'hello, hello' back within trained speaker.
What is the problem?

### To Reproduce

s

### Version

4.0.1

### Platform

win10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by crexlight** [comment]
Your video card or processor must not have enough power to process audio in real time. What are your computer specs? Also try this
`svc vc -m XX -c XX -ab 0.5 -aa 1 -b 1.5`
(try increase `-b` parameter)

**Comment by zdj97** [comment]
ok thanks, I have done this. My cpu is not good enough to infer.
