### ISSUE TITLE
Runtime Error when starting training: Given groups=1, weight of size [192, 256, 5], expected input[5, 768, 790] to have 256 channels, but got 768 channels instead

### ISSUE THREAD

**Issue by KatieBelli** [voicepaw/so-vits-svc-fork#764]
### Describe the bug

When I start training with `svc train -t`, this error always apppears:

> Traceback (most recent call last):
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\Scripts\svc.exe\__main__.py", line 7, in <module>
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\so_vits_svc_fork\__main__.py", line 128, in train
>     train(
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\so_vits_svc_fork\train.py", line 149, in train
>     trainer.fit(model, datamodule=datamodule)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 520, in fit
>     call._call_and_handle_interrupt(
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\lightning\pytorch\trainer\call.py", line 44, in _call_and_handle_interrupt
>     return trainer_fn(*args, **kwargs)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 559, in _fit_impl
>     self._run(model, ckpt_path=ckpt_path)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 935, in _run
>     results = self._run_stage()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 978, in _run_stage
>     self.fit_loop.run()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\lightning\pytorch\loops\fit_loop.py", line 201, in run
>     self.advance()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\lightning\pytorch\loops\fit_loop.py", line 354, in advance
>     self.epoch_loop.run(self._data_fetcher)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\lightning\pytorch\loops\training_epoch_loop.py", line 133, in run
>     self.advance(data_fetcher)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\lightning\pytorch\loops\training_epoch_loop.py", line 220, in advance
>     batch_output = self.manual_optimization.run(kwargs)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\lightning\pytorch\loops\optimization\manual.py", line 90, in run
>     self.advance(kwargs)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\lightning\pytorch\loops\optimization\manual.py", line 109, in advance
>     training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\lightning\pytorch\trainer\call.py", line 288, in _call_strategy_hook
>     output = fn(*args, **kwargs)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\lightning\pytorch\strategies\strategy.py", line 366, in training_step
>     return self.model.training_step(*args, **kwargs)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\so_vits_svc_fork\train.py", line 429, in training_step
>     ) = self.net_g(c, f0, uv, spec, g=g, c_lengths=lengths, spec_lengths=lengths)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\so_vits_svc_fork\modules\synthesizers.py", line 172, in forward
>     x = self.pre(c) * x_mask + self.emb_uv(uv.long()).transpose(1, 2)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\conv.py", line 313, in forward
>     return self._conv_forward(input, self.weight, self.bias)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\conv.py", line 309, in _conv_forward
>     return F.conv1d(input, weight, bias, self.stride,
> RuntimeError: Given groups=1, weight of size [192, 256, 5], expected input[5, 768, 790] to have 256 channels, but got 768 channels instead

### To Reproduce

Following the usual commands to prepare the dataset and then start training.

### Additional context

My guess is this happened after I updated to 4.0.1. I updated to 4.0.2 today but it didn't help.

### Version

4.0.2

### Platform

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by xiatian12345** [comment]
I got the same error!!!!!!

**Comment by KatieBelli** [comment]
No one knows what could be the solution? I uninstalled and reinstalled it but it didn't help.

**Comment by kegidorocts** [comment]
Tried changing all "768" appearance in  config.json file to "256", 
seems is the quickest temporary solution..
At least it is processing now.

**Comment by KatieBelli** [comment]
> Tried changing all "768" appearance in config.json file to "256", seems is the quickest temporary solution.. At least it is processing now.

I started training with the changed config file and changed all "768" appearances like you suggested. Same error appears.

**Comment by kegidorocts** [comment]
> > Tried changing all "768" appearance in config.json file to "256", seems is the quickest temporary solution.. At least it is processing now.
> 
> I started training with the changed config file and changed all "768" appearances like you suggested. Same error appears.

Would you mind posting your config file here, 
and I will post mine too, just want to have a simple comparison.

Actually I only tried `svc infer source.wav`, but not `svc train`, cuz the training was already done..

I checked the inference result of using the changed config file (with the method above), and only got abnormal sounds, although the process was ended without error messages.
So then I tried starting the process with another config file, which was used in the previous training step, and the process was also able to start. This older config file was generated by a different program, therefore is different from the inference one, and I believe the older one is more usable (otherwise the training would fail)..

Back to work place and I will see the result using the older config file.

**Comment by KatieBelli** [comment]
> > > Tried changing all "768" appearance in config.json file to "256", seems is the quickest temporary solution.. At least it is processing now.
> > 
> > 
> > I started training with the changed config file and changed all "768" appearances like you suggested. Same error appears.
> 
> Would you mind posting your config file here, and I will post mine too, just want to have a simple comparison.
> 
> Actually I only tried `svc infer source.wav`, but not `svc train`, cuz the training was already done..
> 
> I checked the inference result of using the changed config file (with the method above), and only got abnormal sounds, although the process was ended without error messages. So then I tried starting the process with another config file, which was used in the previous training step, and the process was also able to start. This older config file was generated by a different program, therefore is different from the inference one, and I believe the older one is more usable (otherwise the training would fail)..
> 
> Back to work place and I will see the result of using the older config file.

Thank you for your help. Here is my current config file (including the changed values that included the number "768"):

> {
>   "train": {
>     "log_interval": 150,
>     "eval_interval": 1850,
>     "seed": 10965,
>     "epochs": 1001,
>     "learning_rate": 0.0005,
>     "betas": [
>       0.8,
>       0.99
>     ],
>     "eps": 1e-09,
>     "batch_size": 5,
>     "fp16_run": false,
>     "bf16_run": false,
>     "lr_decay": 0.999875,
>     "segment_size": 10240,
>     "init_lr_ratio": 1,
>     "warmup_epochs": 0,
>     "c_mel": 45,
>     "c_kl": 1.0,
>     "use_sr": true,
>     "max_speclen": 512,
>     "port": "8001",
>     "keep_ckpts": 10,
>     "num_workers": 8,
>     "log_version": 0,
>     "ckpt_name_by_step": false,
>     "accumulate_grad_batches": 1
>   },
>   "data": {
>     "training_files": "filelists/44k/train.txt",
>     "validation_files": "filelists/44k/val.txt",
>     "max_wav_value": 32256.0,
>     "sampling_rate": 44100,
>     "filter_length": 2048,
>     "hop_length": 512,
>     "win_length": 2048,
>     "n_mel_channels": 80,
>     "mel_fmin": 0.0,
>     "mel_fmax": 22050
>   },
>   "model": {
>     "inter_channels": 192,
>     "hidden_channels": 192,
>     "filter_channels": 256,
>     "n_heads": 2,
>     "n_layers": 6,
>     "kernel_size": 3,
>     "p_dropout": 0.1,
>     "resblock": "1",
>     "resblock_kernel_sizes": [
>       3,
>       7,
>       11
>     ],
>     "resblock_dilation_sizes": [
>       [
>         1,
>         3,
>         5
>       ],
>       [
>         1,
>         3,
>         5
>       ],
>       [
>         1,
>         3,
>         5
>       ]
>     ],
>     "upsample_rates": [
>       8,
>       8,
>       2,
>       2,
>       2
>     ],
>     "upsample_initial_channel": 512,
>     "upsample_kernel_sizes": [
>       16,
>       16,
>       4,
>       4,
>       4
>     ],
>     "n_layers_q": 3,
>     "use_spectral_norm": false,
>     "gin_channels": 256,
>     "ssl_dim": 256,
>     "n_speakers": 200
>   },
>   "spk": {
>     "Britney": 0
>   }
> }

**Comment by kegidorocts** [comment]
Figured out that using the attached config.json will successfully start a training using `svc train -t` .
I copied your config.json and altered it a bit according to mine. 
Don't really know the reason of why it is working, merely gave several tries for the right config.
Hope it works at your side too, like a charm...

[config.json.txt](https://github.com/voicepaw/so-vits-svc-fork/files/11857073/config.json.txt)

**Comment by KatieBelli** [comment]
> Figured out that using the attached config.json will successfully start a training using `svc train -t` . I copied your config.json and altered it a bit according to mine. Don't really know the reason of why it is working, merely gave several tries for the right config. Hope it works at your side too, like a charm...
> 
> [config.json.txt](https://github.com/voicepaw/so-vits-svc-fork/files/11857073/config.json.txt)

This worked! Thank you so much!

It seems that this line after **"mel_fmax": 22050,** solved the problem:

> "contentvec_final_proj": false

That's the only difference I noticed between your attached file and my original file (before I changed the numbers that included "768"). Interesting that the problem is gone by adding that one line.

**Comment by KatieBelli** [comment]
@kegidorocts solved the issue (thank you) so I'm closing with this comment.
