### ISSUE TITLE
auto predict is on, on first pass

### ISSUE THREAD

**Issue by adnjoo** [voicepaw/so-vits-svc-fork#807]
### Describe the bug

When running the GUI program for the first time by clicking Infer, the `Auto predict F0 ...` and `Auto play` boxes will check themselves on

### To Reproduce

1. Open GUI program (I'm clicking the install.bat file on my Windows 10 laptop)
2. Choose model path, config path, input audio path
3. Click Infer 

### Version

4.1.1

### Platform

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

### Screenshots
auto predict and auto play checkboxes are ticked (although they were both unticked when I pressed Infer)
![auto predict](https://github.com/voicepaw/so-vits-svc-fork/assets/22807629/82fcd0e8-bf00-48a4-bf9c-c8fa2b80b6d0)

on second pass onwards, I'm able to leave the auto predict checkbox unticked
![second pass](https://github.com/voicepaw/so-vits-svc-fork/assets/22807629/6a9dc4b0-17d3-4151-b811-326606c41b77)

**Comment by 34j** [comment]
Duplicate

**Comment by adnjoo** [comment]
@34j hi, which issue is the duplicate? 

is there a way to turn off the checkboxes on the first run?

**Comment by kevinlinxc** [comment]
I also have this issue and it's very annoying
