### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '.'

### ISSUE THREAD

**Issue by Patraskon** [voicepaw/so-vits-svc-fork#809]
### Describe the bug

                    PermissionError: [Errno 13] Permission denied: '.'
[16:45:22] INFO     [16:45:22] Event infer, values {'model_path': 'D:/Download/Compressed/knaz/G_3120.pth',  gui.py:665
                    'model_path_browse': 'D:/Download/Compressed/knaz/G_3120.pth', 'config_path': '',
                    'config_path_browse': '', 'cluster_model_path': '', 'cluster_model_path_browse': '',
                    'speaker': '', 'silence_threshold': -35.0, 'transpose': 0.0, 'auto_predict_f0': True,
                    'f0_method': 'crepe', 'cluster_infer_ratio': 0.0, 'noise_scale': 0.4, 'pad_seconds':
                    0.1, 'chunk_seconds': 0.5, 'max_chunk_seconds': 40.0, 'absolute_thresh': True,
                    'input_path': 'D:/Download/44444.ogg', 'input_path_browse': 'D:/Download/44444.ogg',
                    'input_path_folder_browse': '', 'output_path': 'D:/Download/4444444444.wav',
                    'output_path_browse': 'D:/Download/4444444444.wav', 'auto_play': True,
                    'crossfade_seconds': 0.05, 'block_seconds': 0.35, 'additional_infer_before_seconds':
                    0.15, 'additional_infer_after_seconds': 0.1, 'realtime_algorithm': '1 (Divide
                    constantly)', 'input_device': 'Microphone (FIFINE K678 Microph (MME)', 'output_device':
                    'Динамики (Sound BlasterX G6) (MME)', 'passthrough_original': False, 'presets': 'Default
                    File', 'preset_name': '', 'use_gpu': True}
[16:45:25] INFO     [16:45:25] Starting inference...                                                         gui.py:725
           INFO     [16:45:25] Finished inference for 44444.ogg                                              gui.py:151
           ERROR    [16:45:25] Error opening 'D:/Download/4444444444.wav': System error.                     gui.py:157
                    Traceback (most recent call last):
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\g
                    ui.py", line 155, in after_inference
                        play_audio(output_path)
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\g
                    ui.py", line 28, in play_audio
                        data, sr = sf.read(path)
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\soundfile.py",
                    line 285, in read
                        with SoundFile(file, 'r', samplerate, channels,
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\soundfile.py",
                    line 658, in __init__
                        self._file = self._open(file, mode_int, closefd)
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\soundfile.py",
                    line 1216, in _open
                        raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
                    soundfile.LibsndfileError: Error opening 'D:/Download/4444444444.wav': System error.
           ERROR    [16:45:25] Error in realtime:                                                            gui.py:838
           ERROR    [16:45:25] [Errno 13] Permission denied: '.'                                             gui.py:839
                    pebble.common.RemoteTraceback: Traceback (most recent call last):
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\pebble\common.py",
                    line 174, in process_execute
                        return function(*args, **kwargs)
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\i
                    nference\main.py", line 75, in infer
                        svc_model = Svc(
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\i
                    nference\core.py", line 115, in __init__
                        self.hps = utils.get_hparams(config_path)
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\u
                    tils.py", line 430, in get_hparams
                        config = json.loads(Path(config_path).read_text("utf-8"))
                      File "C:\Program Files\Python310\lib\pathlib.py", line 1134, in read_text
                        with self.open(mode='r', encoding=encoding, errors=errors) as f:
                      File "C:\Program Files\Python310\lib\pathlib.py", line 1119, in open
                        return self._accessor.open(self, mode, buffering, encoding, errors,
                    PermissionError: [Errno 13] Permission denied: '.'

                    The above exception was the direct cause of the following exception:

                    Traceback (most recent call last):
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\g
                    ui.py", line 836, in main
                        future.result()
                      File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 451, in result
                        return self.__get_result()
                      File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in
                    __get_result
                        raise self._exception
                    PermissionError: [Errno 13] Permission denied: '.'
           ERROR    [16:45:25] Error in inference:                                                           gui.py:846
           ERROR    [16:45:25] [Errno 13] Permission denied: '.'                                             gui.py:847
                    pebble.common.RemoteTraceback: Traceback (most recent call last):
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\pebble\common.py",
                    line 174, in process_execute
                        return function(*args, **kwargs)
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\i
                    nference\main.py", line 75, in infer
                        svc_model = Svc(
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\i
                    nference\core.py", line 115, in __init__
                        self.hps = utils.get_hparams(config_path)
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\u
                    tils.py", line 430, in get_hparams
                        config = json.loads(Path(config_path).read_text("utf-8"))
                      File "C:\Program Files\Python310\lib\pathlib.py", line 1134, in read_text
                        with self.open(mode='r', encoding=encoding, errors=errors) as f:
                      File "C:\Program Files\Python310\lib\pathlib.py", line 1119, in open
                        return self._accessor.open(self, mode, buffering, encoding, errors,
                    PermissionError: [Errno 13] Permission denied: '.'

                    The above exception was the direct cause of the following exception:

                    Traceback (most recent call last):
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\g
                    ui.py", line 844, in main
                        future.result()
                      File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 451, in result
                        return self.__get_result()
                      File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in
                    __get_result
                        raise self._exception
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\g
                    ui.py", line 836, in main
                        future.result()
                      File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 451, in result
                        return self.__get_result()
                      File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in
                    __get_result
                        raise self._exception
                    PermissionError: [Errno 13] Permission denied: '.'
           ERROR    [16:45:25] Error in realtime:                                                            gui.py:838
           ERROR    [16:45:25] [Errno 13] Permission denied: '.'                                             gui.py:839
                    pebble.common.RemoteTraceback: Traceback (most recent call last):
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\pebble\common.py",
                    line 174, in process_execute
                        return function(*args, **kwargs)
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\i
                    nference\main.py", line 75, in infer
                        svc_model = Svc(
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\i
                    nference\core.py", line 115, in __init__
                        self.hps = utils.get_hparams(config_path)
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\u
                    tils.py", line 430, in get_hparams
                        config = json.loads(Path(config_path).read_text("utf-8"))
                      File "C:\Program Files\Python310\lib\pathlib.py", line 1134, in read_text
                        with self.open(mode='r', encoding=encoding, errors=errors) as f:
                      File "C:\Program Files\Python310\lib\pathlib.py", line 1119, in open
                        return self._accessor.open(self, mode, buffering, encoding, errors,
                    PermissionError: [Errno 13] Permission denied: '.'

                    The above exception was the direct cause of the following exception:

                    Traceback (most recent call last):
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\g
                    ui.py", line 836, in main
                        future.result()
                      File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 451, in result
                        return self.__get_result()
                      File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in
                    __get_result
                        raise self._exception
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\g
                    ui.py", line 844, in main
                        future.result()
                      File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 451, in result
                        return self.__get_result()
                      File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in
                    __get_result
                        raise self._exception
                      File
                    "C:\Users\San\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\so_vits_svc_fork\g
                    ui.py", line 836, in main
                        future.result()
                      File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 451, in result
                        return self.__get_result()
                      File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in
                    __get_result
                        raise self._exception
                    PermissionError: [Errno 13] Permission denied: '.'

### To Reproduce

[https://i.imgur.com/S6HxbHv.png](url)

### Version

4.1.1

### Platform

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by acewins727** [comment]
I think you also need a config path for this one

**Comment by Patraskon** [comment]
The models I use do not have them.


> I think you also need a config path for this one

**Comment by SilentDelirium** [comment]
I'm having the same issue. Following acewins727 advice, I loaded the config JSON file. Anytime I load a JSON config file, the program crashes. Even with different config files.
