### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by GayGod** [voicepaw/so-vits-svc-fork#828]
### Describe the bug

 [08:36:29] Error in realtime:                                                            gui.py:838
           ERROR    [08:36:29] [Errno 13] Permission denied: '.'                                             gui.py:839
                    pebble.common.RemoteTraceback: Traceback (most recent call last):
                      File
                    "C:\Users\Owner\AppData\Roaming\so-vits-svc-fork\venv\lib\site-packages\pebble\common.py
                    ", line 174, in process_execute
                        return function(*args, **kwargs)
                      File

### To Reproduce

just clicked start rvc

### Additional context

i get this error when running realtime vc

### Version

v4.1.1

### Platform

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by GayGod** [comment]
nvm solved

**Comment by 77Mynameislol77** [comment]
> 

very helpful comment

**Comment by 65rayfos** [comment]
What was the fix?

**Comment by token-hub** [comment]
Having the same error. what was the fix?

**Comment by token-hub** [comment]
> Having the same error. what was the fix?

I fixed it by setting the config path. thanks to this [reply](https://github.com/voicepaw/so-vits-svc-fork/issues/546#issuecomment-1532656751)

**Comment by LunarCapita1** [comment]
> > Having the same error. what was the fix?
> 
> I fixed it by setting the config path. thanks to this [reply](https://github.com/voicepaw/so-vits-svc-fork/issues/546#issuecomment-1532656751)

How did you set the config path? I don't have this "config.json" file anywhere needed for this to work, even though I have a pre-trained model.
