### ISSUE TITLE
Warning: f0.py:198: RuntimeWarning: invalid value encountered in divide

### ISSUE THREAD

**Issue by bugfixer21** [voicepaw/so-vits-svc-fork#886]
### Describe the bug

Warning: f0.py:198: RuntimeWarning: invalid value encountered in divide
![Screenshot 2023-08-10 182749](https://github.com/voicepaw/so-vits-svc-fork/assets/75885689/9baec0c1-d268-4c03-aac2-5e6a8196c039)
Issue with division concerning f0.py? I'm not a coder but along with this warning it also seems to run for a very long time without results

### To Reproduce

Unknown. so-vits-svc in general used to work for me but it's been a while (a few months) I installed the latest version and no matter what branch of sovits I install it produces the same results. 
1. Install latest version of fork?
2. Run the program with a model path, config path, and audio path,
3. Results?

### Additional context

It might be possible that I don't have a strong enough CPU (What I use).
Processor	Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, 3192 Mhz, 6 Core(s), 12 Logical Processor(s)
Not sure if that is strong or weak or whatever, but when I try to produce vocals it will literally go on for hours (eg; Image in describe the bug) I'm still new to this whole reporting issues thing so let me know if I missed any important details

### Version

v4.1.1

### Platform

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by 34j** [comment]
I think it is a very minor issue and no need to worry about it.
