### ISSUE TITLE
'svc' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by OssaBellator** [voicepaw/so-vits-svc-fork#896]
### Describe the bug

'svc' is not recognized as an internal or external command,
operable program or batch file.

### To Reproduce

conda create -n so_vits_env python=3.8
conda activate so_vits_env
svc

### Version

latest

### Platform

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by 34j** [comment]
This is because it is not installed.
