### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by coolst3r** [voicepaw/so-vits-svc-fork#968]
### Is your feature request related to a problem? Please describe.

can we add support please

### Describe alternatives you've considered

wine may  work dont know yet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Are you willing to resolve this issue by submitting a Pull Request?

- [X] Yes, I have the time, and I know how to start.
- [X] Yes, I have the time, but I don't know how to start. I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by 34j** [comment]
Actually already supported.

**Comment by coolst3r** [comment]
> Actually already supported.

do know a guide i can follow
