### ISSUE TITLE
!pre-config “Warning” 

### ISSUE THREAD

**Issue by Nefecoban2008** [voicepaw/so-vits-svc-fork#981]
### Describe the bug

While running this command, It gives error 
![IMG_0520](https://github.com/voicepaw/so-vits-svc-fork/assets/122311788/df208a57-7279-4bc1-89d8-f6fe371e5bb7)

### To Reproduce

If you could help me about solving this issue, I would be grateful 

### Version

Last version

### Platform

Google Collab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by Nefecoban2008** [comment]
I solved to this probleme

**Comment by McSombra** [comment]
Hi! Could you please share how you solved the error? Thanks!

**Comment by Daily-Up** [comment]
How did you solve it ?

**Comment by Nefecoban2008** [comment]
You only should ignore to this problem and you should go on following the steps. It won’t create any probleme . I tested this solution before.

**Comment by rudritarahman** [comment]
> I solved to this probleme

How did you solve the problem?
